---
- name: configure all
  hosts: registry
  become: true
  pre_tasks:
    - name: Set hostname
      command: hostnamectl set-hostname registry.fanmode.com
      register: set_hostname
    - name: adding repo for java8
      apt_repository:
        repo:  deb http://ftp.us.debian.org/debian sid main
        state: present
        filename: java8
    - name: Install basic packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - rsync
        - aptitude
        - parted
        - xfsprogs
        - ufw
        - lvm2
        - openjdk-8-jdk
  roles:
    - { role: security }
    - { role: secure_openssh_server }
    - { role: user_management }
    - { role: postfix }
    - { role: apache }
    - { role: certbot }
    - { role: nexus }
